name: health_up
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  crypto: ^3.0.0
  shared_preferences: ^2.2.2
  http: ^1.5.0
  fl_chart: ^0.68.0
  open_file: ^3.3.1
  path_provider: ^2.1.1
  http_parser: ^4.0.2
  file_picker: ^10.3.0
  flutter_svg: ^2.1.1
  lucide_icons: ^0.257.0
  table_calendar: ^3.0.9
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/pill.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21